branches:
  only:
  - master
  - eXXcellent_adaptions
language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty
jdk:
    - oraclejdk8
#    - oraclejdk9
cache:
  directories:
    - $HOME/.m2/repository
# 'true' will skip install step
install: true
script:
    - cp .travis.settings.xml $HOME/.m2/settings.xml
    - mvn clean verify -Ddisable.jetty=false
deploy:
  provider: script
  script: 
      - cp .travis.settings.xml $HOME/.m2/settings.xml
      - mvn deploy:deploy -DskipTests -Djetty.skip
  skip_cleanup: true
  on:
    branch: eXXcellent_adaptions
