branches:
  only:
  - master
  - eXXcellent_adaptions
language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty
jdk:
    - oraclejdk8
#    - oraclejdk9
cache:
  directories:
    - $HOME/.m2/repository
install: false
script:
    - cp .travis.settings.xml $HOME/.m2/settings.xml
    - mvn clean verify
deploy:
  provider: script
  script: 
      - cp .travis.settings.xml $HOME/.m2/settings.xml
      - mvn clean verify deploy:deploy
  skip_cleanup: true
  on:
    tags: false
