language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: false
dist: trusty
services:
- docker
jdk:
    - oraclejdk8
    - oraclejdk9
cache:
  directories:
    - $HOME/.m2/repository
script:
    - cd jpa && mvn clean verify
branches:
  only:
  - master
  - develop
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean verify deploy:deploy"
  skip_cleanup: true
  on:
    tags: true
